const 
    CALL_API = "CALL_API",
    GET_MATADATA = "GET_MATADATA",
    FETCHING_SUCCESS = "FETCHING_SUCCESS",
    FETCHING_FAILED = "FETCHING_FAILED",

    SET_THEME = "SET_THEME"

export {CALL_API,GET_MATADATA,FETCHING_SUCCESS,FETCHING_FAILED,SET_THEME}